Name : "Dileep"
Age : 23
Height : 5.11
Weight : 72

# Variables are like a Containers to storing value.
# Here Name,Age,Height,Weight Are Variable Names....
# Dileep,23,5.11,72 are values...
# These is the process of Variables their Values...